name: CICD workflow

# Events
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  test:
    # runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Generate Environment Variables File
        run: |
          echo "VITE_SUPABASE_BASE_URL=${{ secrets.VITE_SUPABASE_BASE_URL }}" >> .env
          echo "VITE_SUPABASE_API_KEY=${{ secrets.VITE_SUPABASE_API_KEY }}" >> .env
          echo "VITE_SUPABASE_FUNCTIONS_NAVER_BOOK_SEARCH_URL=${{ secrets.VITE_SUPABASE_FUNCTIONS_NAVER_BOOK_SEARCH_URL }}" >> .env
          echo "_API_NAVER_BOOK_SEARCH_BASE_URL=${{ secrets._API_NAVER_BOOK_SEARCH_BASE_URL }}" >> .env
          echo "_API_NAVER_BOOK_SEARCH_ID=${{ secrets._API_NAVER_BOOK_SEARCH_ID }}" >> .env
          echo "_API_NAVER_BOOK_SEARCH_PW=${{ secrets._API_NAVER_BOOK_SEARCH_PW }}" >> .env

      - name: Run the tests
        run: npm test
